# linear regression model on intrusion detection dataset
data<-read.csv("C://lpu//5th sem//INT234//Datasets//intrusion_detection_data.csv")
str(data)
data$class<-factor(data$class)
data$class<-as.numeric(data$class)
model1<-lm(data$class ~ data$duration)
model2<-lm(data$class ~ data$protocol_type)
model3<-lm(data$class~data$service)
model4<-lm(data$class~data$flag)
model5<-lm(data$class~data$src_bytes)
summary(model1)
plot(data$duration,data$class, main = "Linear Regression on intrusion detection",xlab="Duration",ylab="Class",pch=19,col="blue")
abline(model1,col="red")
summary(model2)
summary(model3)
summary(model4)
summary(model5)
